source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'SnapKit', '~> 0.15.0'
pod 'ParseUI', '~> 1.1.7'
pod 'Parse', '~> 1.10.0'
pod 'AlamofireImage', '~> 2.0'
pod 'SwiftSpinner', '~> 0.8.0'
